is_simulation: False
simulation:
    n_robots: 2
    robots: 
        1:  
            pose: [0,20,0]
        2:  
            pose: [0,0,0]
    dimensions: [800, 800]
    constants:
        WALL: 0
        FREE: 1
        OCCUPIED: 2       
real:
    n_robots: 2
    robots:     
        1: 
            pose: [0, 20, 0]
            port: "/dev/cu.HC-05-01-DevB"
            baud_rate: 9600
        2: 
            pose: [0, 0, 0]
            port: "/dev/cu.HC-05-DevB"
            baud_rate: 9600
    dimensions: [800, 800]
gui:
    dimensions_screen: [800, 800]
    dimensions_map: [600, 800]
    dimensions_user: [200, 800]
    frame_rate: 2
    colors:
        background: [255, 255, 255]
        free: [0, 0, 0]
        frontier: [192,192,192]
        robot_1: [255, 120, 120]
        robot_2: [120, 120, 255]
        direction: [0, 200, 100]
        user:
            background: [120, 120, 120]
            button: [120, 0, 0]
            font: [255, 255, 255]
    font:
        name: "couriernew"
        size: 35
    rect_run: [50, 120, 100, 50]
    rect_stop: [50, 200, 100, 50]
    width_line: 5
    width_frontier: 10
    radius_robot: 9
    title: "COEX"
helpers:
    map_orientation:
        'N': 0
        'E': 1
        'S': 2
        'W': 3
    map_type2edges:
        0: ['N', 'E', 'S', 'W']
        1: ['N', 'S', 'W']
        2: ['N', 'E', 'S']
        3: ['E', 'S', 'W']
        4: ['S', 'W']
        5: ['E', 'S']
        6: ['S']
        7: ['N']



























