constants:
    WALL: 0
    FREE: 1
    OCCUPIED: 2
    FRONTIER: 3
gui:
    colors:
        wall: [255, 255, 255]
        free: [0, 0, 0]
        robot: [0, 0, 200]
        direction: [0, 200, 100]
        user-background: [120, 120, 120]
        user-button: [120, 0, 0]
        user-font: [255, 255, 255]
    dimensions_map: [600, 800]
    dimensions_user: [200, 800]
map:
    simulation:
        n_robots: 10
        dimensions: [800, 800]
    real_world:
        n_robots: 1
        robots:     
            1: [0, 0, 0]
        dimensions_map: [600, 800]
    
    


